version: '3.8'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden # change for multiple instances
    restart: always

    networks:
      - bw

    ports:
      - $BWPORTN:80
      - 3012:3012

    volumes:
      - ./bw-data:/data
      - /var/log/docker:/var/log/docker
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    environment:
      - ADMIN_TOKEN=$ADMIN_TOKEN
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true # Change to false after first login
      - INVITATIONS_ALLOWED=true # Send invitation using admin page
      - LOG_FILE=/var/log/docker/bitwarden.log
      - DOMAIN=https://bw.$DOMAINNAME
 
#    labels: # uncomment labels only if on the same VM as Traefik (same Docker host)
#      - "traefik.enable=true"
#      - "traefik.docker.network=proxy"
#      # Entry Point for https
#      - "traefik.http.routers.bitwarden-secure.entrypoints=websecure"
#      - "traefik.http.routers.bitwarden-secure.rule=Host(`bw.$DOMAINNAME`)"
#      - "traefik.http.routers.bitwarden-secure.service=bitwarden-service"
#      - "traefik.http.services.bitwarden-service.loadbalancer.server.port=80"
#      # websocket
#      - "traefik.http.routers.bitwarden-ws.entrypoints=websecure"
#      - "traefik.http.routers.bitwarden-ws.rule=Host(`bw.$DOMAINNAME`) && Path(`/notifications/hub`)"
#      - "traefik.http.middlewares.bitwarden-ws=bw-stripPrefix@file"
#      - "traefik.http.routers.bitwarden-ws.service=bitwarden-websocket"
#      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"

networks:
  bw:
    external: true
