version: '3.8'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    restart: always
    ports:
      - 8686:80
    volumes:
      - ./bw-data:/data
    environment:
      #- ADMIN_TOKEN=
      - WEBSOCKET_ENABLED=true
    networks:
      - bw
#    labels: # use labels only if on the same VM as Traefik (same Docker host)
#      - "traefik.enable=true"
#      - "traefik.docker.network=proxy"
#      # Entry Point for https
#      - "traefik.http.routers.bitwarden-secure.entrypoints=websecure"
#      - "traefik.http.routers.bitwarden-secure.rule=Host(`bw.yourdomain`)"
#      - "traefik.http.routers.bitwarden-secure.service=bitwarden-service"
#      - "traefik.http.services.bitwarden-service.loadbalancer.server.port=80"
#      # websocket
#      - "traefik.http.routers.bitwarden-ws.entrypoints=websecure"
#      - "traefik.http.routers.bitwarden-ws.rule=Host(`bw.yourdomain`) && Path(`/notifications/hub`)"
#      - "traefik.http.middlewares.bitwarden-ws=bw-stripPrefix@file"
#      - "traefik.http.routers.bitwarden-ws.service=bitwarden-websocket"
#      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"
      
networks:
  bw:
    external: true
